[book]
authors = ["Warp"]
language = "es"
multilingual = false
src = "src"
title = "Guía Programación Competitiva"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Wh4rp/guide-competitive-programming"

[output.html.playground]
languages = ["rust", "python", "cpp"]
editable = true

[output.html.code.hidelines]
python = "~"
cpp = "~"